name: union_shop
description: "A Flutter project for the University of Portsmouth union shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  go_router: ^17.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/hero.png
    - assets/product1.png
    - assets/product2.png
    - assets/product3.png
    - assets/product4.png
    - assets/collection_clothing.png
    - assets/hoodie.png
    - assets/tshirt.png
    - assets/sweatshirt.png
    - assets/cap.png
    - assets/backpack.png
    - assets/jacket.png
    - assets/polo.png
    - assets/zip_hoodie.png
    - assets/pants.png
    - assets/scarf.png
    - assets/bottle.png
    - assets/water_bottle.png
    - assets/mug.png
    - assets/laptop_sleeve.png